title: Cédric Félizard
description: Crafting zeros and ones since 1337
email: blog@infertux.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://infertux.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

permalink:     /posts/:year/:month/:day/:title/
paginate_path: /page:num
timezone:      UTC

liquid:
  error_mode: strict

sass:
    style: compressed
    sass_dir: _includes

exclude:
  - vendor # for Travis
  - "*.sh"
  - Gemfile*
  - README.md
